[package]
authors = ["Marcel MÃ¼ller <neikos@neikos.email>"]
description = "A single point database"
documentation = "http://neikos.me/rustbreak/rustbreak/index.html"
homepage = "https://github.com/TheNeikos/rustbreak"
keywords = ["database", "simple", "fast", "daybreak", "rustbreak"]
license = "MPL-2.0"
name = "rustbreak"
readme = "README.md"
repository = "https://github.com/TheNeikos/rustbreak"
version = "2.0.0"

[dependencies]
fs2 = "0.4"
quick-error = "1.1.0"
ron = "0.1.2"
serde_yaml = { version = "0.7", optional = true }
serde = "1"

[dev-dependencies]
lazy_static = "0.2.1"
tempfile = "2.1"
serde_derive = "1"

[features]
yaml = ["serde_yaml"]
ron_enc = ["ron"]
